apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=flux-memcached.flux-system
            - --memcached-service=
            - --git-poll-interval=1m
            - --sync-interval=5m
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --k8s-allow-namespace=playground
            - --git-url=git@github.com:bbockelm/flux-get-started
            - --git-user=bbockelm
            - --git-email=bbockelm@users.noreply.github.com
            - --git-path=namespaces,workloads
            - --git-branch=master
            - --git-readonly
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: playground
